---
format: gfm
---

# #TidyTuesday #PydyTuesday: An Introduction to the Weekly Data Challenge

Code and slides for the PyData Northern Utah workshop.

## Project Organization

- `/figures` PNG images and plots.
- `/presentations` Presentation slides.
- `/.quarto` Hidden Quarto project library, not pushed.
- `/.venv` Hidden Python project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version file.
- `LICENSE` MIT License for "as is" permission.
- `README.md` GitHub-flavored markdown README rendered from `README.qmd`.
- `README.qmd` Quarto markdown README to edit and render into `README.md`.
- `_quarto.yml` Quarto project configuration file.
- `pyproject.toml` Python project environment configuration file.
- `uv.lock` Python project environment lockfile.

## Project Environment

After cloning this repository, go to the project's terminal in Positron and run `uv run` to create the `/.venv` project library and install the specified Python and library versions.

For more details on using Python, Positron, GitHub, Quarto, etc. see the recommended [data stack](https://github.com/marcdotson/data-stack).

